version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=mysql+pymysql://enrolluser:enrollpass@db/campus_interview
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - db
    volumes:
      - ./app:/app/app

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=campus_interview
      - MYSQL_USER=enrolluser
      - MYSQL_PASSWORD=enrollpass
      - MYSQL_ROOT_PASSWORD=rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    # COMMENT: Adjust these MySQL settings based on your requirements
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=256M

volumes:
  mysql_data:   